<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="Description" content="Ici le contenu">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="public/images/site/favicon-48x48.png">
        <link rel="stylesheet" type="text/css" href="public/css/style.css"/>
        <title>Domotique</title>
    </head>
    <body>
        <header>

        </header>
        <div class="container">
            <main>
                <?php if(isset($template) && $template !==""): ?>
                    <?php include $template . '.phtml' ?>
                <?php endif; ?>
            </main>
        </div>

        <footer>

        </footer>
        <script src="public/js/libraries/vueV2.6.12.js"></script>
        <script src="public/js/main.js"></script>
        <script src="public/js/panel.js"></script>
        <script src="public/js/graph.js"></script>
    </body>
</html>