<form method="post" id="login_form" class="mainFrame">
    <fieldset>
        <legend>Login</legend>
        <ul>
            <li>
                <label for="loginEmail">Email</label>
                <input id="loginEmail" name="email" type="text"  maxlength="100" required value="">
            </li>
            <li>
                <label for="loginPassword" >Mot de passe</label>
                <input id="loginPassword" name="password" type="password"  maxlength="60" required value="">
            </li>
        </ul>
        <button class="submitButton" id="loginButton" type="submit">Se connecter</button>
        <div class="errorMessage" id="errorLogin"></div>
    </fieldset>
</form>